<a href="https://colab.research.google.com/github/sedecasa/AP155/blob/main/Matrices_P2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# problem 4.17
import numpy as np

inA = np.array([4., 4, 8, 4, 4, 5, 3, 7, 8, 3, 9, 9, 4, 7, 9, 5]).reshape(4, 4)
inbs = np.array([1., 2, 3, 4])

def backsub(U, bs):   #performs back substitution
  n = bs.size
  xs = np.zeros(n)
  for i in reversed(range(n)):
    xs[i] = (bs[i] - U[i, i+1:]@xs[i+1:])/U[i, i]
  return xs

def gauelim(inA, inbs):   #performs gaussian elimination
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size

  #performs elementary row operations so the matrix becomes triangular
  for j in range(n-1):
    for i in range(j+1, n):
      coeff = A[i, j]/A[j, j]   #calculates the coefficient for row elimination
      A[i, j:] -= coeff * A[j, j:]
      bs[i] -= coeff * bs[j]

  print(A)
  print(bs)
  xs = backsub(A, bs)
  return xs

print(gauelim(inA, inbs))

[[  4.   4.   8.   4.]
 [  0.   1.  -5.   3.]
 [  0.   0. -32.  16.]
 [  0.   0.   0.   0.]]
[1. 1. 6. 3.]
[nan nan inf inf]


/tmp/ipython-input-555807959.py:11: RuntimeWarning: divide by zero encountered in scalar divide
  xs[i] = (bs[i] - U[i, i+1:]@xs[i+1:])/U[i, i]
/tmp/ipython-input-555807959.py:11: RuntimeWarning: invalid value encountered in matmul
  xs[i] = (bs[i] - U[i, i+1:]@xs[i+1:])/U[i, i]


In [ ]:
# problem 4.17

def gauelim_aug(inA, inbs):   #performs gaussian elimination
  A = np.copy(inA)
  bs = np.copy(inbs)
  n = bs.size

  for j in range(n-1):
    for i in range(j+1, n):
      coeff = A[i, j]/A[j, j]
      A[i, j:] -= coeff * A[j, j:]
      bs[i] -= coeff * bs[j]

  if np.all(A[n-1] == 0) and bs[i] != 0:   #replaces the A_33th element to a nonzero value
    A[n-1, n-1] = 10**(-20)
  xs = backsub(A, bs)
  return xs

print(gauelim_aug(inA, inbs))

[-4.5e+20 -1.5e+20  1.5e+20  3.0e+20]


In [ ]:
# problem 4.18

def termcrit(xolds, xnews):   #termination criterion
  errs = np.abs((xnews - xolds)/xnews)
  return np.sum(errs)

def jacobi(n, kmax, tol):   #jacobi interative method
  xnews = np.zeros(n)

  for k in range(1, kmax):
    xs = np.copy(xnews)

    for i in range(n):
      if i == 0:
        xnews[i] = (1 + xs[i+1] + xs[n-1])/4
      if i == n-1:
        xnews[i] = (1 + xs[0] + xs[n-2])/4
      else:
        xnews[i] = (1 + xs[i-1] + xs[i+1])/4
    err = termcrit(xs, xnews)
    if err < tol:
      break

  else:
    xnews = None
  return xnews

print(jacobi(10, 21, 10**(-5)))

def cyctri(n):   #generates an nxn cyclic tridiagonal matrix
  A = np.zeros((n, n))
  A[0, 0] = 4
  A[0, 1] = -1
  A[0, -1] = -1
  for i in range(1, n):
    A[i] = np.roll(A[i-1], 1)
  return A

A = cyctri(10)
bs = np.ones((10))
print(np.linalg.solve(A, bs))

[0.49999952 0.49999952 0.49999952 0.49999952 0.49999952 0.49999952
 0.49999952 0.49999952 0.49999952 0.49999952]
[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]]


In [ ]:
# problem 4.18

print(jacobi(20, 22, 10**(-5)))

A = cyctri(20)
bs = np.ones((20))
print(np.linalg.solve(A, bs))

[0.49999976 0.49999976 0.49999976 0.49999976 0.49999976 0.49999976
 0.49999976 0.49999976 0.49999976 0.49999976 0.49999976 0.49999976
 0.49999976 0.49999976 0.49999976 0.49999976 0.49999976 0.49999976
 0.49999976 0.49999976]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5]
